name: python-docker-workflow
on: 
  push : 
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Buildx
      uses: docker/setup-buildx-activity@v3
    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: classwork-docker-latest
